export const listingCategories = [
  { label: "Electronics & Gadgets", image: "/images/earpod.png" },
  { label: "Furniture & Home Decor", image: "/images/floating/blue-chair.png" },
  { label: "Clothing & Fashion", image: "/images/categories/clothing-fashion.svg" },
  { label: "Shoes & Footwear", image: "/images/sneaker.png" },
  { label: "Accessories & Jewelry", image: "/images/categories/accessories-jewelry.svg" },
  { label: "Vehicles & Auto Parts", image: "/images/categories/auto-parts.svg" },
  { label: "Books & Education", image: "/images/categories/books-education.svg" },
  { label: "Hobbies & Leisure", image: "/images/categories/hobbies-leisure.svg" },
  { label: "Sports & Outdoor", image: "/images/categories/sports-outdoor.svg" },
  { label: "Kitchen & Home Essentials", image: "/images/categories/kitchen-home.svg" },
  { label: "Tools & DIY", image: "/images/categories/tools-diy.svg" },
  { label: "Collectibles & Antiques", image: "/images/categories/collectibles-antiques.svg" },
  { label: "Toys & Games", image: "/images/categories/toys-games.svg" },
  { label: "Other", image: "/images/categories/other.svg" },
];
